version: '3'
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: [ "--config", "/etc/otel-collector-config.yml" ]
    volumes:
      - ./.docker/otel-collector/otel-collector-config.yml:/etc/otel-collector-config.yml

  go-service-a:
    container_name: go-service-a
    build:
      context: service-a/
      dockerfile: Dockerfile.prod
    environment:
      - EXTERNAL_CALL_URL=http://go-service-b:8181
      - OTEL_SERVICE_NAME=go-service-a
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
      - zipkin

  go-service-b:
    container_name: go-service-b
    build:
      context: service-b/
      dockerfile: Dockerfile.prod
    environment:
      - OTEL_SERVICE_NAME=go-service-b
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=8181
    ports:
      - "8181:8181"
    depends_on:
      - otel-collector
      - zipkin
