# Stage 1: Build Stage
FROM golang:1.21.3 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o serviceb ./cmd

# Stage 2: Development Stage
FROM golang:1.21.3
WORKDIR /app
COPY --from=builder /app .
CMD ["sh"]